export const loanData = [
    {
      "id": 1,
      "loan_no": "L28U3247",
      "loan_type": "Home Loan",
      "borrower": "Vedika Sachar",
      "borrower_address": "83 Yogi Ganj, Kadapa-058720",
      "co_borrower_1_name": "Divit Vora",
      "co_borrower_1_address": "24/543, Acharya Path Ongole-052360",
      "current_dpd": 91,
      "sanction_amount": "₹ 1934608",
      "region": "West",
      "status": "Approved"
    },
    {
      "id": 2,
      "loan_no": "L28U3243",
      "loan_type": "Car Loan",
      "borrower": "Hrishita Agrawal",
      "borrower_address": "86/622, Deo Path, Berhampore 841186",
      "co_borrower_1_name": "Mahika Tak",
      "co_borrower_1_address": "58 Tella Road, Sultan Pur Majra 918878",
      "current_dpd": 100,
      "sanction_amount": "₹ 1842143",
      "region": "West",
      "status": "Rejected"
    },
    {
      "id": 3,
      "loan_no": "L28U3248",
      "loan_type": "Home Loan",
      "borrower": "Priyansh Chanda",
      "borrower_address": "24, Ray Chowk Cuttack 803932",
      "co_borrower_1_name": "Zain Ghosh",
      "co_borrower_1_address": "H.No. Sp, Dugar Street Kolhapur-543900",
      "current_dpd": 100,
      "sanction_amount": "₹ 2681712",
      "region": "West",
      "status": "Pending"
    },
    {
      "id": 4,
      "loan_no": "L28U3249",
      "loan_type": "Home Loan",
      "borrower": "Hrishita Sen",
      "borrower_address": "94/36 Barad, Hubli-Dharwad-408790",
      "co_borrower_1_name": "Shray Kala",
      "co_borrower_1_address": "63/66, Bharadwaj Street Bokaro 662204",
      "current_dpd": 100,
      "sanction_amount": "₹ 4456808",
      "region": "West",
      "status": "Approved"
    },
    {
      "id": 5,
      "loan_no": "L28U3265",
      "loan_type": "Personal Loan",
      "borrower": "Vivaan Yrik",
      "borrower_address": "H.No. 653 Dada Ganj Ichalkaranji 279923",
      "co_borrower_1_name": "Elakshi Chahal",
      "co_borrower_1_address": "16/45 Divan Road Jabalpur 962051",
      "current_dpd": 76,
      "sanction_amount": "₹ 3863514",
      "region": "West",
      "status": "Rejected"
    },
    {
      "id": 6,
      "loan_no": "L28U3264",
      "loan_type": "Car Loan",
      "borrower": "Nirvaan Mander",
      "borrower_address": "543 Singhal Street, Bahlawa Jahangir Pur-348320",
      "co_borrower_1_name": "Vihaan Dua",
      "co_borrower_1_address": "H.No. 115, Saha Road Singrauli 049374",
      "current_dpd": 90,
      "sanction_amount": "₹ 1256863",
      "region": "West",
      "status": "Pending"
    },
    {
      "id": 7,
      "loan_no": "L28U3266",
      "loan_type": "Personal Loan",
      "borrower": "Nirvi Sahni",
      "borrower_address": "41/42, Duo, Amroha-741195",
      "co_borrower_1_name": "Dhankul Lalla",
      "co_borrower_1_address": "48/41, Garde Path Uluberia 709396",
      "current_dpd": 76,
      "sanction_amount": "₹ 2687368",
      "region": "East",
      "status": "Approved"
    },
    {
      "id": 8,
      "loan_no": "L57P1290",
      "loan_type": "Home Loan",
      "borrower": "Aryan Vashisht",
      "borrower_address": "23/78, Azure Street, Dehradun-248001",
      "co_borrower_1_name": "Tanisha Kapoor",
      "co_borrower_1_address": "12/34, Sunrise Avenue, Roorkee-247667",
      "current_dpd": 102,
      "sanction_amount": "₹ 3187654",
      "region": "North",
      "status": "Overdue"
    },
    {
      "id": 9,
      "loan_no": "L64M3421",
      "loan_type": "Business Loan",
      "borrower": "Samar Mehta",
      "borrower_address": "54/90, Link Road, Surat-395007",
      "co_borrower_1_name": "Rhea Dutta",
      "co_borrower_1_address": "87/12, MG Road, Vadodara-390001",
      "current_dpd": 45,
      "sanction_amount": "₹ 2745320",
      "region": "West",
      "status": "Approved"
    },
    {
      "id": 10,
      "loan_no": "L79R4823",
      "loan_type": "Education Loan",
      "borrower": "Ishaan Bhatt",
      "borrower_address": "89/76, Orchid Lane, Jaipur-302012",
      "co_borrower_1_name": "Neha Bhatt",
      "co_borrower_1_address": "89/76, Orchid Lane, Jaipur-302012",
      "current_dpd": 30,
      "sanction_amount": "₹ 1357890",
      "region": "North",
      "status": "Approved"
    },
    {
      "id": 11,
      "loan_no": "L22T7586",
      "loan_type": "Car Loan",
      "borrower": "Pranav Deshmukh",
      "borrower_address": "76/45, Unity Street, Pune-411007",
      "co_borrower_1_name": "Mira Deshmukh",
      "co_borrower_1_address": "76/45, Unity Street, Pune-411007",
      "current_dpd": 0,
      "sanction_amount": "₹ 689450",
      "region": "West",
      "status": "Approved"
    },
    {
      "id": 12,
      "loan_no": "L34B6709",
      "loan_type": "Personal Loan",
      "borrower": "Ritika Bansal",
      "borrower_address": "41/55, Bloom Lane, Howrah-711101",
      "co_borrower_1_name": "Vikrant Bansal",
      "co_borrower_1_address": "58/22, Crystal Road, Durgapur-713216",
      "current_dpd": 78,
      "sanction_amount": "₹ 2437890",
      "region": "East",
      "status": "Approved"
    },
    {
      "id": 13,
      "loan_no": "L12A8954",
      "loan_type": "Home Loan",
      "borrower": "Aarav Kapoor",
      "borrower_address": "12/98, Lotus Park, Mumbai-400001",
      "co_borrower_1_name": "Nisha Kapoor",
      "co_borrower_1_address": "34/76, Breeze Lane, Thane-400601",
      "current_dpd": 90,
      "sanction_amount": "₹ 2873640",
      "region": "West",
      "status": "Approved"
    },
    {
      "id": 14,
      "loan_no": "L56T3897",
      "loan_type": "Business Loan",
      "borrower": "Raghav Nair",
      "borrower_address": "23/76, Spice Avenue, Kochi-682001",
      "co_borrower_1_name": "Ananya Nair",
      "co_borrower_1_address": "12/45, Pearl Lane, Thiruvananthapuram-695001",
      "current_dpd": 56,
      "sanction_amount": "₹ 1987342",
      "region": "South",
      "status": "Approved"
    },
    {
      "id": 15,
      "loan_no": "L89C7452",
      "loan_type": "Car Loan",
      "borrower": "Dev Singh",
      "borrower_address": "45/98, Harmony Road, Lucknow-226001",
      "co_borrower_1_name": "Isha Singh",
      "co_borrower_1_address": "23/78, Crystal Path, Kanpur-208001",
      "current_dpd": 10,
      "sanction_amount": "₹ 789540",
      "region": "North",
      "status": "Approved"
    },
    {
      "id": 16,
      "loan_no": "L67X4389",
      "loan_type": "Personal Loan",
      "borrower": "Simran Kaur",
      "borrower_address": "12/67, Rose Villa, Chandigarh-160017",
      "co_borrower_1_name": "Kabir Kaur",
      "co_borrower_1_address": "45/89, Pine Street, Mohali-160055",
      "current_dpd": 23,
      "sanction_amount": "₹ 1567340",
      "region": "North",
      "status": "Approved"
    },
    {
      "id": 17,
      "loan_no": "L34F9876",
      "loan_type": "Education Loan",
      "borrower": "Ayesha Khan",
      "borrower_address": "78/12, Green Avenue, Hyderabad-500032",
      "co_borrower_1_name": "Farhan Khan",
      "co_borrower_1_address": "12/67, Blue Street, Secunderabad-500003",
      "current_dpd": 35,
      "sanction_amount": "₹ 987560",
      "region": "South",
      "status": "Approved"
    },
    {
      "id": 18,
      "loan_no": "L93U5734",
      "loan_type": "Home Loan",
      "borrower": "Priya Mehta",
      "borrower_address": "34/89, Sunshine City, Ahmedabad-380001",
      "co_borrower_1_name": "Vivek Mehta",
      "co_borrower_1_address": "23/45, Maple Street, Vadodara-390001",
      "current_dpd": 0,
      "sanction_amount": "₹ 3456789",
      "region": "West",
      "status": "Approved"
    },
    {
      "id": 19,
      "loan_no": "L88H2765",
      "loan_type": "Business Loan",
      "borrower": "Ravi Joshi",
      "borrower_address": "78/90, Central Avenue, Indore-452001",
      "co_borrower_1_name": "Sneha Joshi",
      "co_borrower_1_address": "56/12, Lake Road, Bhopal-462001",
      "current_dpd": 64,
      "sanction_amount": "₹ 2378900",
      "region": "Central",
      "status": "Approved"
    },
    {
      "id": 20,
      "loan_no": "L42K9832",
      "loan_type": "Car Loan",
      "borrower": "Rajiv Verma",
      "borrower_address": "32/45, Coral Street, Delhi-110001",
      "co_borrower_1_name": "Suman Verma",
      "co_borrower_1_address": "89/76, Violet Road, Noida-201301",
      "current_dpd": 15,
      "sanction_amount": "₹ 654320",
      "region": "North",
      "status": "Approved"
    },
    {
      "id": 21,
      "loan_no": "L29M1276",
      "loan_type": "Personal Loan",
      "borrower": "Reena Shah",
      "borrower_address": "12/98, Sunrise Avenue, Jaipur-302012",
      "co_borrower_1_name": "Anil Shah",
      "co_borrower_1_address": "67/89, Pink Street, Jodhpur-342001",
      "current_dpd": 80,
      "sanction_amount": "₹ 2783450",
      "region": "North",
      "status": "Approved"
    },
    {
      "id": 22,
      "loan_no": "L38Q5632",
      "loan_type": "Education Loan",
      "borrower": "Tanya Raj",
      "borrower_address": "45/67, Bloom Valley, Patna-800001",
      "co_borrower_1_name": "Ashok Raj",
      "co_borrower_1_address": "56/98, Elite Road, Gaya-823001",
      "current_dpd": 60,
      "sanction_amount": "₹ 1345678",
      "region": "East",
      "status": "Approved"
    },
    {
      "id": 23,
      "loan_no": "L82V4035",
      "loan_type": "Home Loan",
      "borrower": "Vikram Soni",
      "borrower_address": "78/34, Hill Top, Pune-411001",
      "co_borrower_1_name": "Sheetal Soni",
      "co_borrower_1_address": "56/21, Rock Street, Nashik-422005",
      "current_dpd": 20,
      "sanction_amount": "₹ 3278900",
      "region": "West",
      "status": "Approved"
    },

  ]



